Repository choffmann/budget-binder, pull requests merged in 2022-05, with the labels that each got.

#22 Implement Ktor Client
  Dockerfile
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/APIResponse.kt
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/ErrorModel.kt
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/User.kt
  budget-binder-multiplatform-app/build.gradle.kts
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/android/MainActivity.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/model/Platform.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/ApplicationFlow.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/client/Client.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/common/DataResponse.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/client/Client.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/AuthRepositoryImplementation.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/UserRepositoryImplementation.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/AuthRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/UserRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/auth_user/LoginUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/get_user/UserUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/model/HelloWorld.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/model/Platform.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/UserViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/desktop/Main.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/model/Platform.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de.hsfl.budgetBinder.common/Constants.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de.hsfl.budgetBinder.model/Platform.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de.hsfl.budgetBinder/compose/ApplicationView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/App.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/ApplicationView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/LoginView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/UserView.kt
  budget-binder-server/build.gradle.kts
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/main.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/UserModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/AuthRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/BaseRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/UserRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/JWTService.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/UserService.kt
  budget-binder-server/src/main/resources/openapi.json
  budget-binder-server/src/main/resources/openapi.yaml
  build.gradle.kts
  gradlew
Labels: client

#25 Getting Multiplattform Compose to Work
  budget-binder-common/build.gradle.kts
  budget-binder-multiplatform-app/build.gradle.kts
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/desktop/Main.kt
  budget-binder-multiplatform-app/src/desktopMain/resources/icon.icns
  budget-binder-multiplatform-app/src/desktopMain/resources/icon.ico
  budget-binder-multiplatform-app/src/desktopMain/resources/icon.png
  gradle.properties
Labels: client

#32 Refactored the start of the server
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/main.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
Labels: backend

#35 created the Config Class to host all env-variables
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/Config.kt
Labels: enhancement, backend

#37 Patch build.gradle.kts - Update TargetFormats.AppImage
  budget-binder-multiplatform-app/build.gradle.kts
Labels: bug

#36 7 creating lofi
  docs/Low-Fidelity_Prototyp.md
Labels: documentation

#33 27 ssl self signed for better local testing
  budget-binder-server/README.md
  budget-binder-server/build.gradle.kts
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/main.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/AuthRoutes.kt
Labels: enhancement, backend

#31 30 finish data models with children and parents
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/Category.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/CategoryModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/EntryModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/UserService.kt
Labels: backend

#45 send APIResponse if answer is 401
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
Labels: enhancement, backend

#50 Update the server to 2.0.1 with kodein 8.0.0beta
  budget-binder-server/build.gradle.kts
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/UserPrincipal.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/AuthRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/BaseRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/CategoryRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/EntryRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/UserRoutes.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/ApplicationTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/CategoryEntryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/CategoryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/EntryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/TestHelpers.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/TestRequests.kt
Labels: enhancement, backend

#51 Implement Navigation Drawer
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/Constants.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeAppBar.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRoot.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRouter.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeScreen.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/StateManager.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/navigation/PrototypeDrawerContent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/categories/Categories.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/home/Home.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/screen1/Screen1.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/screen2/Screen2.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/settings/Settings.kt
Labels: prototype, frontend

#53 Implement Welcome Screen
  budget-binder-multiplatform-app/build.gradle.kts
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/WelcomeImages.kt
  budget-binder-multiplatform-app/src/androidMain/res/drawable/welcome_getstarted_undraw.xml
  budget-binder-multiplatform-app/src/androidMain/res/drawable/welcome_screen1_undraw.xml
  budget-binder-multiplatform-app/src/androidMain/res/drawable/welcome_screen2_undraw.xml
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/WelcomeImages.kt
  budget-binder-multiplatform-app/src/desktopMain/resources/welcomeScreen/undraw_awesome_rlvy.svg
  budget-binder-multiplatform-app/src/desktopMain/resources/welcomeScreen/undraw_savings_re_eq4w.svg
  budget-binder-multiplatform-app/src/desktopMain/resources/welcomeScreen/undraw_welcome_re_h3d9.svg
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRouter.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeScreen.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/StateManager.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/Welcome.kt
Labels: prototype, frontend

#64 Settings Screen - Implement Snackbar and more
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRoot.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/StateManager.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/settings/Settings.kt
Labels: enhancement, prototype, frontend

#60 59 serve js client with bb server
  .dockerignore
  Dockerfile
  Dockerfile_builder
  Dockerfile_dev
  budget-binder-common/src/commonMain/resources/ico/BudgetBinderCircle.ico
  budget-binder-server/files/favicon.ico
  budget-binder-server/files/openapi.json
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/BaseRoutes.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/ApplicationTest.kt
Labels: enhancement, backend, client
