Repository choffmann/budget-binder, pull requests merged in 2022-06, with the labels that each got.

#68 HiFi Implement Login/Register View
  budget-binder-multiplatform-app/build.gradle.kts
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/LoginImpl.kt
  budget-binder-multiplatform-app/src/androidMain/res/drawable/ic_budgetbinder.xml
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/LoginImpl.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeData.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRoot.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeRouter.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/PrototypeScreen.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/StateManager.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/navigation/PrototypeAppBar.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/UiState.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/Login.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/Register.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/prototype/screens/welcome/Welcome.kt
Labels: prototype, frontend

#80 Implement RESTAPI Client
  budget-binder-multiplatform-app/build.gradle.kts
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/client/Client.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/AuthRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/CategoryRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/EntryRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/UserRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/AuthRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/CategoryRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/EntryRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/UserRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/auth_user/LoginUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/auth_user/LogoutUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/auth_user/RegisterUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/use_case/get_user/UserUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/AuthUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/CategoriesUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/EntriesUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/UserUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/LogoutViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/RegisterViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/UserViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/CategoryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/EntryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/RegisterViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/SettingsViewModel.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/user/UserComponent.kt
Labels: frontend, client

#84 74 web implement dashboard logic
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/StateManager.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/resources/cart.png
Labels: frontend, web

#85 Web compose frontend
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/StateManager.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/ApplicationView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateOnRegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
  budget-binder-multiplatform-app/src/jsMain/resources/cart.png
  budget-binder-multiplatform-app/src/jsMain/resources/images/Logo.png
  budget-binder-multiplatform-app/src/jsMain/resources/index.html
  budget-binder-multiplatform-app/src/jsMain/resources/material-design.css
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/UserComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/UserView.kt
Labels: frontend, web

#86 74 web implement dashboard logic
  CopyScriptJsMain.ps1
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/StateManager.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
Labels: frontend, web

#67 Add lofi test evaluation
  docs/Low-Fidelity_Prototyp.md
  docs/img/low-fidelity_prototype/change_1_post.png
  docs/img/low-fidelity_prototype/change_1_pre.png
  docs/img/low-fidelity_prototype/change_2_post.png
  docs/img/low-fidelity_prototype/change_3_post.png
Labels: documentation, prototype, user tests

#87 Web compose frontend - new Icons for Category.Image
  CopyScriptJsMain.ps1
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/Category.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcons.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/StateManager.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsChangeUserDataView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
  budget-binder-multiplatform-app/src/jsMain/resources/index.html
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/TestModels.kt
Labels: frontend, web

#96 Cookie file storage
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/android/BudgetBinderApplication.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/data/client/plugins/getCookieFileStorage.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/data/client/plugins/getCookieFileStorage.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/data/client/plugins/FileCookieStorage.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/data/client/plugins/SerializableCookie.kt
Labels: enhancement, frontend, client, desktop, android

#98 Implement Login / Register / Settings View
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/compose/dialog/DeleteUserDialog.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/androidMain/res/drawable/ic_avataricon.xml
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/SettingsUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/UiEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/register/RegisterEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/register/RegisterTextFieldState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/register/RegisterViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/EditUserEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/EditUserState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsEditUserViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/dialog/DeleteUserDialog.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/desktopMain/resources/undraw_profile_pic_ic-5-t.svg
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Router.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/dialog/DeleteUserDialog.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcons.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/textfield/EmailTextField.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/textfield/SettingsTextField.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/Settings.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsEditUserView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsMenuView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsServerUrlView.kt
Labels: frontend, desktop, android

#101 100 cors entfernen
  budget-binder-server/build.gradle.kts
  budget-binder-server/data/config_sample.yaml
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/config/Config.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/config/ConfigIntermediate.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/mainModule.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/JWTService.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/TestHelpers.kt
Labels: backend

#103 91 web implement dashboard style restlogic
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
Labels: frontend, web

#102 90 implement and style categorysummary
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/CategoryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
Labels: frontend, web

#108 Fix wrong images used. Fix padding of images. Set image container to …
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
Labels: frontend, web

#110 109 web entryoverview screen
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/EntryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryOverviewView.kt
Labels: frontend, web

#112 105 web implement and style create entry view
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/EntryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsChangeUserDataView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
Labels: frontend, web

#107 "Keine Kategorie" ist im Backend jetzt auch "null" und weiterer Backend Stuff
  budget-binder-server/files/openapi.json
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/CategoryModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/EntryModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/models/UserModel.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/routes/CategoryRoutes.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/implementations/CategoryServiceImpl.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/implementations/EntryServiceImpl.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/implementations/UserServiceImpl.kt
  budget-binder-server/src/main/kotlin/de/hsfl/budgetBinder/server/services/interfaces/EntryService.kt
  budget-binder-server/src/main/resources/openapi.yaml
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/ApplicationTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/CategoryEntryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/CategoryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/EntryTest.kt
  budget-binder-server/src/test/kotlin/de/hsfl/budgetBinder/server/TestRequests.kt
Labels: enhancement, backend

#116 114 web implement and style categoryedit
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/CategoryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategorySummaryView.kt
Labels: frontend, web

#115 Implement NavDrawer Viewmodel
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/NavDrawerViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/NavDrawer.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcons.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsMenuView.kt
Labels: frontend, desktop, android, clean architecture

#113 Implement Dashboard Viewmodel
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/client/Client.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/data/repository/CategoryRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/CategoryRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/CategoriesUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/DashboardUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/UiEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardEntryState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Router.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
Labels: frontend, client, clean architecture

#118 Add form in entryEdit and add categoryList in entryEdit and entryOver…
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryOverviewView.kt
Labels: frontend, web

#123 121 web restructure settingviews with new viewmodel
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/NavBar.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsChangeUserDataView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
Labels: frontend, web

#125 120 entry viewmodel
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/EntryUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/EntryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryInputState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryOverviewView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
Labels: frontend, web, clean architecture

#126 Rework EntryViewModel and various Web compose frontend stuff
  budget-binder-common/src/commonMain/kotlin/de/hsfl/budgetBinder/common/Category.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/EntryUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/EntryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/category/edit/CategoryEditViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryInputState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/common/Constants.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/CategoryComposables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/NavBar.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Router.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategoryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/dashboard/DashboardView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/login/LoginView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/register/RegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsChangeUserDataView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/settings/SettingsView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/presentation/CategoryIcon.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryCreateOnRegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryDetailView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryOverviewView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsChangeUserDataView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
  budget-binder-multiplatform-app/src/jsMain/resources/cart.png
  budget-binder-multiplatform-app/src/jsMain/resources/images/Loading.gif
  budget-binder-multiplatform-app/src/jsMain/resources/material-design-override.css
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/category/CategorySummary.kt
Labels: frontend, web, clean architecture

#129 128 web collection of small stuff
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/CategoryComposables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/NavBar.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
Labels: frontend, web

#131 130 web load older entries correctly
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/main.kt
Labels: frontend, web

#133 132 web show category color with entry on dashboard
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardEntryState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardFocusedCategoryState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardState.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/dashboard/DashboardViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/theme/AppStylesheet.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryOverviewView.kt
Labels: frontend, web

#135 Change TopBar on Login and Register
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/compose/dialog/ServerUrlDialog.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/AuthUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/ToggleServerUrlDialogUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/Screen.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/AuthViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/register/RegisterViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/category/CategoryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsEditUserViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/dialog/ServerUrlDialog.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/NavDrawer.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Router.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/category/CategorySummary.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
Labels: frontend

#137 Sync OS Darkmode
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/data/repository/SettingsRepositoryImpl.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/di/DI.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/repository/SettingsRepository.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/AppResetUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/DataFlowUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/SettingsUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/SettingsUseCases.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/StoreUserStateUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/ToggleDarkModeUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/storage/StoreDarkModeUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/domain/usecase/storage/StoreServerUrlUseCase.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/flow/DarkModeFlow.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/flow/UserFlow.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/RootViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/AuthViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/login/LoginViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/auth/register/RegisterViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/entry/EntryViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/navdrawer/NavDrawerViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsEditUserViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsViewModel.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/welcome/WelcomeEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/welcome/WelcomeViewModel.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/dialog/ServerUrlDialog.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcon.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/data/repository/SettingsRepositoryImpl.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/data/repository/SettingsRepositoryImpl.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/NavDrawer.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Root.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/compose/icon/AppIcons.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/Settings.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsMenuView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/welcome/WelcomeComponent.kt
Labels: frontend

#138 136 improve visualisation of older entry list
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/category/summary/CategorySummaryEvent.kt
  budget-binder-multiplatform-app/src/commonMain/kotlin/de/hsfl/budgetBinder/presentation/viewmodel/settings/SettingsEditUserViewModel.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/CategoryComposables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/Composables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/DashboardComposables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/compose/EntryComposables.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategoryCreateOnRegisterView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/category/CategorySummaryView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/dashboard/DashboardComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryOverviewView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/login/LoginComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/register/RegisterComponent.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsChangeUserDataView.kt
Labels: frontend, web

#139 Change font of "Categories:" Text in Create/Edit-Entry
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jsMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryEditView.kt
Labels: frontend, web

#140 Compose jvm entry
  budget-binder-multiplatform-app/src/androidMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryDropDownCategory.kt
  budget-binder-multiplatform-app/src/desktopMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryEditCategory.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/Router.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryComponent.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryCreateView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryDetailView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryEditView.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/entry/EntryFormular.kt
  budget-binder-multiplatform-app/src/jvmMain/kotlin/de/hsfl/budgetBinder/screens/settings/SettingsMenuView.kt
Labels: frontend
